<a href="https://colab.research.google.com/github/martinpius/TensorFlow_Graph_Functions/blob/main/Tensorflow_Layers_and_Models_Building_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Setting up the colab environment:
from google.colab import drive
try:
  drive.mount("/content/drive", force_remount = True)
  COLAB = True
  import tensorflow as tf
  print(f"You are using Google colab with tensorflow version: {tf.__version__}")
except:
  COLAB = False
  print('Please setup the colab environment:')

def time_fmt(x):
  h = int(x/(60*60))
  m = int(x%(60*60)/60)
  s = int(x%60)
  return f"{h}: {m:>03}: {s:>05.2f}"

Mounted at /content/drive
You are using Google colab with tensorflow version: 2.3.1


In [3]:
#Importing necessary packs
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import time
import timeit
from datetime import datetime
plt.style.use('fivethirtyeight')
%load_ext tensorboard
%matplotlib inline

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [4]:
#Creating, saving and resoring tensorflow models from scratch (tf building blocks (layers, models, variables))

In [5]:
#A simple tensorflow module example
class MytfModule(tf.Module):
  def __init__(self, name = None):
    super(MytfModule, self).__init__(name = name)
    self.var_train = tf.Variable(initial_value = 3.1467, trainable = True, name = 'trainable_variable')
    self.var_non_train = tf.Variable(initial_value = 12.8, trainable = False, name = 'non_trainable_variable')
  
  def __call__(self, inputs):
    out = tf.multiply(self.var_train, inputs) + self.var_non_train
    return out
mymodule = MytfModule(name = 'test')
mymodule(tf.constant(2, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=19.0934>

In [6]:
#Subclassing
print(f"Total variables: {mymodule.variables}\nTrainable variables: {mymodule.trainable_variables}\nNon trainable variables: {mymodule.var_non_train}")

Total variables: (<tf.Variable 'non_trainable_variable:0' shape=() dtype=float32, numpy=12.8>, <tf.Variable 'trainable_variable:0' shape=() dtype=float32, numpy=3.1467>)
Trainable variables: (<tf.Variable 'trainable_variable:0' shape=() dtype=float32, numpy=3.1467>,)
Non trainable variables: <tf.Variable 'non_trainable_variable:0' shape=() dtype=float32, numpy=12.8>


In [7]:
#Tensorflow linear dense layer
class tfLinear(tf.Module):
  def __init__(self, a, b, name = None):
    super(tfLinear, self).__init__(name = name)
    self.w = tf.Variable(tf.random.normal([a, b]), name = 'weight')
    self.b = tf.Variable(tf.zeros(b,),name = 'bias')
  def __call__(self, inputs):
    out = tf.matmul(inputs, self.w) + self.b
    return tf.nn.relu(out)

mylinear = tfLinear(4,4)
x = tf.ones(shape = [2,4])
mylinear(x)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.       , 0.       , 1.7085505, 1.2305462],
       [0.       , 0.       , 1.7085505, 1.2305462]], dtype=float32)>

In [8]:
#A complete two layers sequential model
class CModel(tf.Module):
  def __init__(self, name = None):
    super(CModel, self).__init__(name = name)
    self.l1 = tf.keras.layers.Dense(units = 32,activation = 'relu')
    self.l2 = tf.keras.layers.Dense(units = 10, activation = 'softmax')
  def __call__(self, inputs):
    inputs = self.l1(inputs)
    inputs = self.l2(inputs)
    return inputs

cmodel = CModel(name = 'test')
x = tf.ones(shape = (2,2))
cmodel(x)


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.17658514, 0.09391515, 0.07037135, 0.0852779 , 0.05337677,
        0.07467252, 0.0968036 , 0.10545976, 0.09042767, 0.15311007],
       [0.17658514, 0.09391515, 0.07037135, 0.0852779 , 0.05337677,
        0.07467252, 0.0968036 , 0.10545976, 0.09042767, 0.15311007]],
      dtype=float32)>

In [9]:
print(f"sub_modules: {cmodel.submodules}")

sub_modules: (<tensorflow.python.keras.layers.core.Dense object at 0x7f65286d8940>, <tensorflow.python.keras.layers.core.Dense object at 0x7f65286daf28>)


In [10]:
for k in cmodel.variables: #Print detail for each trainable variable
  print(k,'\n')

<tf.Variable 'dense/kernel:0' shape=(2, 32) dtype=float32, numpy=
array([[ 0.12897786,  0.10890433, -0.33441052,  0.28452018,  0.2852464 ,
        -0.15534422, -0.3122832 ,  0.39866433,  0.19821563, -0.22019611,
        -0.05265513, -0.1443544 , -0.02657965,  0.02315024,  0.2558603 ,
        -0.10767114, -0.19219545,  0.1552752 ,  0.3089246 ,  0.17077151,
         0.195954  , -0.28949094,  0.4002737 , -0.1664494 ,  0.3734571 ,
        -0.10096711, -0.13449857, -0.02573293, -0.18366829, -0.1416493 ,
        -0.22424291,  0.29258713],
       [-0.09529549, -0.11160946, -0.24085566, -0.11641082, -0.22366932,
         0.07784143,  0.3689737 , -0.18405828, -0.10549673, -0.30272382,
        -0.1231387 ,  0.06713006,  0.16042951, -0.01923853, -0.02091515,
         0.3865808 ,  0.36309835,  0.4029124 ,  0.30634424,  0.3944935 ,
         0.38910505,  0.16134706,  0.09669384,  0.2941853 , -0.37184057,
        -0.13992262, -0.24770972,  0.12811676, -0.15779933, -0.11655846,
        -0.22917518, -0

In [11]:
#Differing the input shape to be defined later in the process
class LayerDiff(tf.Module):
  def __init__(self,units, name = None):
    super(LayerDiff, self).__init__(name = name)
    self.built = False
    self.units = units
  def __call__(self,inputs):
    if not self.built:
      self.w = tf.Variable(tf.random.normal([inputs.shape[-1], self.units]), name = 'w')
      self.b = tf.Variable(tf.zeros([self.units]), name = 'b')
      self.built = True
    out = tf.matmul(inputs, self.w) + self.b
    return tf.nn.relu(out)


In [12]:
layer2 = LayerDiff(units = 32, name = 'dense_1')
layer2(tf.constant([[2.0,1.2,4.2,1.3]], dtype = tf.float32))

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[0.12075353, 0.5491103 , 0.        , 0.        , 4.1164203 ,
        0.        , 5.001314  , 0.        , 0.        , 4.128237  ,
        0.        , 3.0755625 , 0.9339832 , 0.        , 5.397764  ,
        0.        , 0.        , 0.        , 0.        , 1.1700965 ,
        0.        , 5.8723135 , 6.8778067 , 0.        , 8.695045  ,
        2.6232352 , 0.        , 2.789588  , 0.        , 0.        ,
        3.0459366 , 0.        ]], dtype=float32)>

In [13]:
#We can use the above layer by stacking to create a keras sequential model as follow:
class MySequential(tf.Module):
  def __init__(self, name = None):
    super(MySequential, self).__init__(name = name)
    self.l1 = LayerDiff(units = 128, name = 'dense_1')
    self.l2 = LayerDiff(units = 64, name = 'dense_2')

  def __call__(self, inputs):
    inputs = self.l1(inputs)
    return self.l2(inputs)

myseq = MySequential()
print(myseq(tf.constant([[22.1,21.9,11.7,21.8,22.,18.9]])))


tf.Tensor(
[[   0.         43.34645     0.        356.30545   201.97498     0.
     0.          0.        440.9583    413.65805     0.          0.
     0.        342.6621     81.71755    98.726585    0.          0.
     0.          0.        234.5314    255.41422     0.        737.33844
     0.          0.          0.          0.          0.          0.
   686.3242    654.6912      0.          0.          0.          0.
     0.          0.        174.3163    446.2407    435.45282   414.924
   413.672     786.61487    17.557755  561.9615    228.11806     0.
   366.72495   114.405624    0.        225.60645     0.        118.908775
  1360.7952    118.551254  311.09283   599.37537    46.557144  489.6618
     0.        346.27753   317.04926   162.05762 ]], shape=(1, 64), dtype=float32)


In [14]:
#Saving the models weight for future use(without the architecture of the model)
chkp_path = "mypath"
Checkpoint = tf.train.Checkpoint(model = myseq)


In [15]:
Checkpoint.write(chkp_path)
Checkpoint.write(chkp_path)

'mypath'

In [16]:
ls mypath* #To get the content of the directory

mypath.data-00000-of-00001  mypath.index


In [17]:
try: 
  tf.train.list_variables(chkp_path)
except Exception as e:
  print(f"{type(e)}: {e}")

In [18]:
#Re-load the model's weight by overriding the original
new_seq = MySequential()
new_checkpoint = tf.train.Checkpoint(model = new_seq)
new_checkpoint.restore('mypath')

In [20]:
#try the reloaded model
new_seq(tf.constant([[2.3,3.1,2.]]))

<tf.Tensor: shape=(1, 64), dtype=float32, numpy=
array([[ 0.        , 19.49403   , 28.065937  , 20.493654  ,  0.        ,
         0.        ,  0.        , 27.487549  , 11.420691  ,  0.        ,
         0.        , 13.330731  ,  8.503112  , 48.825157  ,  2.7374225 ,
         0.        , 23.163027  ,  0.3695402 ,  0.        ,  0.        ,
         0.        , 21.348148  ,  0.        ,  2.770853  ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        70.81597   , 44.85498   ,  0.        ,  3.3824253 , 33.1372    ,
         0.        ,  1.9296751 ,  0.        ,  5.382282  ,  0.        ,
         0.        , 16.82231   ,  0.        , 19.365557  ,  0.        ,
         0.14954281,  0.        ,  0.        ,  3.2604165 ,  0.        ,
        24.502707  , 15.198119  , 32.02542   , 34.12722   , 18.4076    ,
        12.440171  , 14.074172  , 20.661797  ,  0.        , 50.719875  ,
        10.694959  , 21.383207  ,  0.        ,  0.        ]],
      dtype=f

In [21]:
#Saving functions using graph.
class NewModel(tf.Module):
  def __init__(self, name = None):
    super(NewModel, self).__init__(name = name)
    self.dense1 = tf.keras.layers.Dense(units = 128, activation = 'relu')
    self.dense2 = tf.keras.layers.Dense(units = 10, activation = 'softmax')

  @tf.function#To allow computational graph
  def __call__(self, inputs):
    inputs = self.dense1(inputs)
    return self.dense2(inputs)

model = NewModel(name = 'Test')


In [22]:
display(model(tf.constant([[2.1,3.3,2.1,2.8]])))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.07235826, 0.04270705, 0.13283753, 0.06921989, 0.141531  ,
        0.06215461, 0.03465841, 0.28989214, 0.09057181, 0.06406926]],
      dtype=float32)>

In [29]:
#Tracing the graph through the tensorboard to visualize
time_stamp = datetime.now()
dir_log = '/logs/func/%s' % time_stamp
file_writer = tf.summary.create_file_writer(dir_log)
model1 = NewModel(name = 'Test')#Call the model again
tf.summary.trace_on(graph = True, profiler = True)
m = print(model1(tf.constant([[2.1,2.3,2.5,1.3]])))
with file_writer.as_default():
  tf.summary.trace_export(name = 'mytest',
                          step = 0,
                          profiler_outdir = dir_log)


tf.Tensor(
[[0.16655011 0.12352917 0.0835418  0.11369362 0.02807372 0.1005584
  0.11611107 0.08334519 0.13152821 0.05306866]], shape=(1, 10), dtype=float32)


In [30]:
tf.saved_model.save(model1, 'test_model') #save the whole model for sharing

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: test_model/assets


In [31]:
ls -l test_model #check the saved model

total 24
drwxr-xr-x 2 root root  4096 Nov 19 09:33 assets/
-rw-r--r-- 1 root root 16042 Nov 19 09:33 saved_model.pb
drwxr-xr-x 2 root root  4096 Nov 19 09:33 variables/


In [33]:
ls -l test_model/variables

total 16
-rw-r--r-- 1 root root 8726 Nov 19 09:33 variables.data-00000-of-00001
-rw-r--r-- 1 root root  381 Nov 19 09:33 variables.index
